### ISSUE TITLE
Bold tag (<b>) is not working in OneScript with default theme template.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Scripting-Toolkit#1]
Bold tag is not working in OneScript with default theme template. Refer below example.
Example: 
            q1 "For this receipt, < b>including  yourself< /b>, please select the number of adults, teens and children who were included in the purchase." info;

Note: In the above example space is added in bold tag to avoid text becoming bold in this comment.

**Comment by dougmorris** [comment]
I have check this with the following question:

```
  Q7 "Please<b> drag</b> and drop  the images into the group which most suits your preference.<bucket/><mandatory>false</mandatory>" style(control(type="Bucket")) loop {
        a "<img id='0' src='https://api.1pt.mobi/i/media?mediaid=88297&mediatype=png' alt='image' width='80' height='80' class='dragdrop'> "    factor(1),
        b "<img id='1' src='https://api.1pt.mobi/i/media?mediaid=88294&mediatype=png' alt='image' width='80' height='80' class='dragdrop'> "    factor(2)
    }
    fields - (
        bucket1 integer;
        bucket2 integer;
        bucket3 integer;

    );
```
I can confirm that the basic HTML being generated includes the bold tags, but they are not being picked up. I think this is a UI issue. I am making @hitesh-opg and @onepointpb aware of this issue too!

**Comment by shobhitOne** [comment]
@onepointpb @hitesh-opg Please checkout the modified reset.css from git and verify it.

**Comment by onepointpb** [comment]
Placed the latest `reset.css` file on staging. It is working now. Will move it to Live as well.
