### ISSUE TITLE
"Enhancement" Need capability to perform addition and subtraction on date value

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Scripting-Toolkit#2]
"Enhancement" Need capability to perform addition and subtraction on date value.
Examples: datenow()+7, datenow()-7

**Comment by dougmorris** [comment]
A DateAdd Library function has been created to support Date Arithmetic:

DateAdd(Value, Interval, Count)

Value is the date that you want the interval added to.
Interval can be:
"yyyy" | Year
"q" | Quarter
"m" | Month
"d" | Day
"y" | Day
"w" | Day
"ww" | Week
"h" | Hour
"n" | Minute
"s" | Second

Count specifies the number of intervals to add (a negative number implies a subtraction).
